\documentclass{article}
\input{../config/commontex}

\title{Installation of a local ACNUC socket server on your machine (under development)}
\author{Penel, S.}

\begin{document}
\SweaveInput{../config/commonrnw.rnw}
\maketitle
\tableofcontents
% BEGIN - DO NOT REMOVE THIS LINE



%%%%%%%%%%%%%%%%%%%%%%%
\section{Introduction}
%%%%%%%%%%%%%%%%%%%%%%%

This chapter is under development and not complete.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{System requirement}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Basically if you are installing \Rlogo{} from the
sources, you should be able to build a ACNUC socket server.
The socket server will build under a number of common Unix and Unix-alike
platforms. You will need several tools: programs are written in C thus 
you will need a
means of compiling C (as gcc compilation tools for linux or unix, Apple
Developer Tools  for MacOSX). You need as well library zlib and sockets
(standards on linux and unix).

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Technical description of the racnucd daemon}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Technical information about the acnuc socket server is available at this url:
\url{http://pbil.univ-lyon1.fr/databases/acnuc/racnucd.html}.


\section{ACNUC remote access protocol}
Description of the socket communication protocol with acnuc is availble at this url:
\url{http://pbil.univ-lyon1.fr/databases/acnuc/remote_acnuc.html}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Setting a local ACNUC database to be queried by the server}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

First of all yo need an ACNUC database, built by yourself or  downloaded from the PBIL ftp server.
An ACNUC database is composed of two sets of files:
\begin{enumerate}
	\item  the acnuc index files.
	\item  the database files (\textit{i.e.} flat files in EMBL/GenBank or SwissProt format).
\end{enumerate}

These two sets will be located  in the \textit{acnuc} and  \textit{gcgacnuc} directories  respectively.
(Directories \textit{acnuc} and  \textit{gcgacnuc} may be identical however it is prefered to use two distict directories.)

An example of an ACNUC database is available on the PBIL ftp server  at this url:
\url{ftp://pbil.univ-lyon1.fr/pub/seqinr/demoacnuc/acnucdatabase.tar.Z}.
 
You may install the database as it follows:
Let ACNUC\_HOME be the base directory for ACNUC intallation.

<<makeACNUCHOME,fig=F,eval=T>>=
dir.create("../ACNUC_HOME", showWarning = FALSE)
@ 

\begin{itemize}
\item Dowload the ACNUC database.

% Mettre eval=F apres premier download
<<dowloadacnucdemo,fig=F,eval=F>>=
download.file("ftp://pbil.univ-lyon1.fr/pub/seqinr/demoacnuc/acnucdatabase.tar.Z",
destfile = "acnucdatabase.tar.Z")
@ 

\item Copy the  acnucdatabase.tar.Z file  into ACNUC\_HOME.

<<moveacnuc,fig=F,eval=T>>=
system("cp acnucdatabase.tar.Z ../ACNUC_HOME")
@ 

\item Uncompress and untar the \texttt{acnucdatabase.tar.Z} file 

<<decompressacnuc,fig=F,eval=T>>=
pwd <- getwd()
setwd("../ACNUC_HOME")
system("gunzip -f acnucdatabase.tar.Z")
system("tar -xvf acnucdatabase.tar")
system("rm -f acnucdatabase.tar")
setwd(pwd)
@ 

\end{itemize}
Now you sould get the following directories:
\begin{verbatim}
ACNUC_HOME/acnucdatabase/index
ACNUC_HOME/acnucdatabase/flat_files
\end{verbatim}

<<showacnuchomecontent,fig=F,eval=T>>=
dir("../ACNUC_HOME")
@ 
which are the   \textit{acnuc} and  \textit{gcgacnuc} directories  respectively.

This database contains the complete genome of \textit{Escherichia coli K12 W3110} and
\textit{Saccharomyces cerevesiae}.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Build the ACNUC sockets server from the sources.}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Once you have a local  ACNUC database available on your server you need to install the sockets server.

\subsection{Download the sources.}
The code source of the racnucd server is available on the PBIL server  at this url:
\begin{verbatim}
http://pbil.univ-lyon1.fr/databases/acnuc/racnucd.html
\end{verbatim}
Alternatively you can download directly  the source from the ftp at:
\begin{verbatim}
ftp://pbil.univ-lyon1.fr/pub/acnuc/unix/racnucd.tar
\end{verbatim}

\subsection{Build the ACNUC sockets server.}
You may install the racnucd server as it follows:
let RACNUCD\_HOME be the base directory for the socket.

<<makeRACNUCCDHOME,fig=F,eval=T>>=
dir.create("../RACNUCD_HOME", showWarning = FALSE)
@

\begin{itemize}
\item Dowload the \texttt{racnucd.tar} file.

% Mettre eval=F apres premier download
<<dowloadracnucd,fig=F,eval=T>>=
download.file("ftp://pbil.univ-lyon1.fr/pub/acnuc/unix/racnucd.tar",
destfile = "racnucd.tar")
@

\item Copy the \texttt{racnucd.tar} file into RACNUCD\_HOME.

<<moveracnucd,fig=F,eval=T>>=
system("cp racnucd.tar ../RACNUCD_HOME")
@ 

\item Untar the \texttt{racnucd.tar} file 

<<decompressacnuc,fig=F,eval=T>>=
setwd("../RACNUCD_HOME")
system("tar -xvf racnucd.tar")
system("rm -f racnucd.tar")
setwd(pwd)
@ 

\end{itemize}
Now you sould get the following directory:
\begin{verbatim}
RACNUCD_HOME/racnucd
\end{verbatim}

<<checkracnucd,fig=F,eval=T>>=
dir("../RACNUCD_HOME")
@ 

Go into RACNUCD\_HOME/racnucd/ and type;
\begin{verbatim}
make
\end{verbatim}
This should create the \textbf{racnucd} executable.

<<makeracuc,fig=F,eval=T>>=
setwd("../RACNUCD_HOME/racnucd")
system("make")
dir(pattern = "racnucd")
setwd(pwd)
@ 

\subsection{Setting the ACNUC sockets server.}
The server is configured by several parameters described in a configuration file \textbf{racnuc.ini}.
The \textbf{racnucd.ini} file is structued as follows:

\begin{verbatim}
port=5558
maxtime=8000
known_db_file=knowndbs
db_env_names=dbplaces
\end{verbatim}

<<showmeracnunini,fig=F,eval=T>>=
ini <- readLines("../RACNUCD_HOME/racnucd/racnucd.ini")
cat(ini, sep = "\n")
@ 

\begin{itemize}
\item \textbf{knowndbs} is a file containing the list of available databases
\item \textbf{dbplaces} is a file containing the path of the available databases
\end{itemize}

The \textbf{knowndbs} contains:
\begin{verbatim}
embl | on |    | EMBL sequence data library | 
swissprot   | on |  | UniProt |
\end{verbatim}

<<showmeknowdbs,fig=F,eval=T>>=
knowndbs <- readLines("../RACNUCD_HOME/racnucd/knowndbs")
cat(knowndbs, sep = "\n")
@ 

Each line defines a database,  the four fields indicating respectively the name
 of the database, its status  (\textit{on} or \textit{off}), a tag and a short description.

The \textbf{dbplaces} contains:
\begin{verbatim}
setenv  swissprot       '/Users/mgouy/Documents/acnuc/petite/swissprot /Users/mgouy/Documents/acnuc/petite/swissprot'
setenv  embl    '/Users/mgouy/Documents/acnuc/petite/embl /Users/mgouy/Documents/acnuc/petite/embl'
\end{verbatim}

<<showmedbplaces,fig=F,eval=T>>=
dbplaces <- readLines("../RACNUCD_HOME/racnucd/dbplaces")
cat(dbplaces, sep = "\n")
@

Each line set the acnuc and gcgacnuc variables for each   database.

Then you should set the files \textbf{knowndbs} and \textbf{dbplaces} according to your installation.
Let's call the database you installed previously \textit{demoacnuc}.
Modify  the \textbf{knowndbs} as follows:
\begin{verbatim}
demoacnuc | on |    | Demo Database | 
\end{verbatim}

<<modifyknowndbs,fig=F,eval=T>>=
writeLines("demoacnuc | on |    | Demo Database | ", "../RACNUCD_HOME/racnucd/knowndbs")
knowndbs <- readLines("../RACNUCD_HOME/racnucd/knowndbs")
cat(knowndbs, sep = "\n")
@ 

and modify  the \textbf{dbplaces} as follows:

\begin{verbatim}
setenv  demoacnuc       'ACNUC_HOME/acnucdatabase/index ACNUC_HOME/acnucdatabase/flat_files'
\end{verbatim}

<<modifydbplaces,fig=F,eval=T>>=
indexpath <- normalizePath("../ACNUC_HOME/index")
ffpath <- normalizePath("../ACNUC_HOME/flat_files")
newdb <- paste("setenv demoacnuc '", indexpath, " ", ffpath, "'", sep = "", collapse = "")
writeLines(newdb, "../RACNUCD_HOME/racnucd/dbplaces")
dbplaces <- readLines("../RACNUCD_HOME/racnucd/dbplaces")
cat(dbplaces, sep = "\n")
@

Finaly, in the RACNUCD\_HOME/racnucd/ directory, type
\begin{verbatim}
./racnucd racnucd.ini
\end{verbatim}

The server should launch and say:
\begin{verbatim}

*******************************************************
Start of remote acnuc server : Tue Oct 16 15:46:16 2007

\end{verbatim}


<<startserver,fig=F,eval=T>>=
setwd("../RACNUCD_HOME/racnucd")
system("./racnucd racnucd.ini > racnucd.log &")
Sys.sleep(1)
system("ps | grep racnucd", intern = TRUE)
cat(readLines("racnucd.log"), sep = "\n")
setwd(pwd)
@ 

The server is now ready.

\subsection{Using seqinR to query your local socket server.}
Launch \Rlogo{}, load the \texttt{seqinr} package  and type

\begin{Schunk}
\begin{Sinput}
choosebank(host="my_machine.domaine",info=T)
\end{Sinput}
\end{Schunk}
for example:

\begin{Schunk}
\begin{Sinput}
choosebank(host="semle.univ-lyon1.fr",info=T)
\end{Sinput}
\end{Schunk}

<<trylocalserver,fig=F,eval=T>>=
library(seqinr)
system("hostname", intern = TRUE) -> hostname
hostname
choosebank(host = hostname, info = TRUE)
@ 

You should obtain something like:
\begin{Schunk}
\begin{Soutput}
       bank status
1 demoacnuc     on
                                                                 info
1 ACNUC database example. (September 2007) Last Updated: Oct 15, 2007
\end{Soutput}
\end{Schunk}

You can now query the database. For example:

<<tryquery,fig=F,eval=T>>=
choosebank(bank = "demoacnuc", host = hostname)
query("mylist", "k=rib@ prot@")
mylist$nelem
sapply(mylist$req, getName)
@ 


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Building your own  ACNUC database. (under development)}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
One of the interest of a local server is to be able use your own ACNUC
database.

\subsection{System requirements.}
 
ACNUC runs on UNIX systems, Windows NT/95/98/00/XP, MacOS 9/X. Tested UNIX
systems include SUN, Linux on PC, IBM RS/6000, Silicon Graphics, DEC Alpha,
Fujitsu UXP/M. ACNUC should be easily installed on any other UNIX platforms. 

\subsection{Database requirements.}

ACNUC database are build from flat files in several possible format : EMBL, Genbank or
SwissProt.Inustructions tp install ACNUC databases are given at this url :
\begin{verbatim}
http://pbil.univ-lyon1.fr/databases/acnuc/localinstall.html
\end{verbatim}


\subsection{Download the ACNUC dababase management tools.}
 
 
 
 
 The code source of the ACNUC tools server are available on the PBIL server  at this url:
\begin{verbatim}
ftp://pbil.univ-lyon1.fr/pub/acnuc/unix/acnucsoft.tar
\end{verbatim}

\subsection{Install the ACNUC dababase management tools.}
ANCUC management tools are described at this url :
\begin{verbatim}
http://pbil.univ-lyon1.fr/databases/acnuc/acnuc_gestion.html
\end{verbatim}
let ACNUC\_SOFT be the base directory for the ACNUC softs.

<<make ACNUC_SOFT,fig=F,eval=T>>=
dir.create("../ACNUC_SOFT", showWarning = FALSE)
@

\begin{itemize}
\item Dowload the \texttt{acnucsoft.tar} file.

% Mettre eval=F apres premier download
<<dowloadacnucsoft,fig=F,eval=T>>=
download.file("ftp://pbil.univ-lyon1.fr/pub/acnuc/unix/acnucsoft.tar",
destfile = "acnucsoft.tar")
@

\item Copy the \texttt{acnucsoft.tar} file into ACNUC\_SOFT.

<<moveacnucsoft,fig=F,eval=T>>=
system("cp acnucsoft.tar ../ACNUC_SOFT")
@ 

\item Untar the \texttt{acnucsoft.tar} file 

<<decompressacnucsoft,fig=F,eval=T>>=
setwd("../ACNUC_SOFT")
system("tar -xvf acnucsoft.tar")
system("rm -f acnucsoft.tar")
setwd(pwd)
@ 

\end{itemize}
Now you sould get the soft sources in following directory:
\begin{verbatim}
ACNUC_SOFT
\end{verbatim}

<<checkracnucd,fig=F,eval=T>>=
dir("../ACNUC_SOFT")
@ 

Go into ACNUC\_SOFT/ and type;
\begin{verbatim}
make
\end{verbatim}
This should create the ACNUC management tools and ACNUC querying tools.

<<makeacucsoft,fig=F,eval=T>>=
setwd("../ACNUC_SOFT/")
system("make")
dir()
setwd(pwd)
@ 

 
 
\subsection{Database building}
You can now build your own database.
All you need is a flat files
in EMBL, GenBank or SwissProt format. You can download a file example at :
\begin{verbatim}
ftp://pbil.univ-lyon1.fr/pub/seqinr/demoacnuc/escherichia_uniprot.dat.Z
\end{verbatim}

Let's use this SwissProt file to build your database
\begin{itemize}

\item Let ACNUC\_MYDB be the directory for your databases.


<<make ACNUC_MYDB,fig=F,eval=T>>=
dir.create("../ACNUC_MYDB", showWarning = FALSE)
@
This directory should contain the two \textit{acnuc} and \textit{gcgacnuc} directories: usually the directories are named.
\textit{index} and \textit{flat\_files}.

<<make ACNUC_MYDB_sousdir,fig=F,eval=T>>=
dir.create("../ACNUC_MYDB/index", showWarning = FALSE)
dir.create("../ACNUC_MYDB/flat_files", showWarning = FALSE)
@

\item Download the \texttt{escherichia\_uniprot.dat.Z} file.

% Mettre eval=F apres premier download
<<dowloadacnucflat,fig=F,eval=T>>=
download.file("ftp://pbil.univ-lyon1.fr/pub/seqinr/demoacnuc/escherichia_uniprot.dat.Z",
destfile = "escherichia_uniprot.dat.Z")
@

\item Copy the \texttt{escherichia\_uniprot.dat.Z} file into ACNUC\_MYDB/flat\_files.

<<moveacnucflat,fig=F,eval=T>>=
system("cp escherichia_uniprot.dat.Z ../ACNUC_MYDB/flat_files")
@ 

\item Uncompress the \texttt{escherichia\_uniprot.dat.Z} file 

<<decompressacnucflat,fig=F,eval=T>>=
setwd("../ACNUC_MYDB/flat_files")
system("gunzip -f escherichia_uniprot.dat.Z")
setwd(pwd)
@ 

\end{itemize}
A simple building of the index can be done with the script  \texttt{buildindex.csh} available at:

\begin{verbatim}
ftp://pbil.univ-lyon1.fr/pub/seqinr/demoacnuc/buildindex.csh
\end{verbatim}


% Mettre eval=F apres premier download
<<dowloadacnucscript,fig=F,eval=T>>=
download.file("ftp://pbil.univ-lyon1.fr/pub/seqinr/demoacnuc/buildindex.csh",
destfile = "buildindex.csh")
@

You can copy this file in ../ACNUC\_MYDB/ and execute it:

\begin{verbatim}
./buildindex.csh escherichia_uniprot
\end{verbatim}

% Mettre eval=F apres premier download
<<dowloadacnucscript,fig=F,eval=T>>=
download.file("ftp://pbil.univ-lyon1.fr/pub/seqinr/demoacnuc/buildindex.csh",
destfile = "buildindex.csh")
system("cp buildindex.csh ../ACNUC_MYDB")
setwd("../ACNUC_MYDB")
system("chmod +x ./buildindex.csh")
system("./buildindex.csh escherichia_uniprot >  ./build.log")
cat(readLines("build.log",50), sep = "\n")
cat(tail(readLines("build.log"),50), sep = "\n")
setwd(pwd)
@
You can check the building in the \texttt{build.log} file.






\section{Misc} 
%%%%%%%%%%%%%

Other tools for acnuc

Several powerful tools dedicated to query ACNUC databases are available. 

The programs \textbf{query} and \textbf{query\_win} allow to query an ACNUC database according to the same
criteria than described  in seqinR. It allows as well several functionality to extact biological data.
\textbf{query\_win} is a graphical version of query.
\textbf{query} is an on-line version which allows to query and ACNUC database through scripts.
Both \textbf{query} and  \textbf{query\_win} are available as a
\textit{client} or a \textit{local} application. More information on these programs can be found at:
\begin{verbatim}
http://pbil.univ-lyon1.fr/software/query_win.html
\end{verbatim}. 




\section{Citation} 
%%%%%%%%%%%%%

If you use query\_win or query in a published work, please cite the following reference:
Gouy M, Gautier C, Attimonelli M, Lanave C, di Paola G. (1985)
 ACNUC--a portable retrieval system for nucleic acid sequence databases: 
 logical and physical designs and usage.. CABIOS, 1, 167-172. 


\SweaveInput{../config/sessionInfo.rnw}

% END - DO NOT REMOVE THIS LINE

%%%%%%%%%%%%  BIBLIOGRAPHY %%%%%%%%%%%%%%%%%
\clearpage
\addcontentsline{toc}{section}{References}
\bibliographystyle{plain}
\bibliography{../config/book}
\end{document}
