\documentclass{article}
\input{../config/commontex}

\title{Installation of a local ACNUC socket server on your machine (under development)}
\author{Penel, S.}

\begin{document}
\SweaveInput{../config/commonrnw.rnw}
\maketitle
\tableofcontents
% BEGIN - DO NOT REMOVE THIS LINE



%%%%%%%%%%%%%%%%%%%%%%%
\section{Introduction.}
%%%%%%%%%%%%%%%%%%%%%%%

This chapter is under development and not complete.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{System requirement.}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

The socket server will  build under a number of common Unix and Unix-alike
platforms.  In addition, binary distributions are available for the most
common Linux distributions and for Mac OS X  (XXX to be done XXX ).If you wish
to install the server from sources, or if you want to build an ACNUC database,
you will need several tools: programs are written in C thus you will need a
means of compiling C (as gcc compilation tools For Linux or Unix , Apple
Developer Tools  for MacOSX ). You need as well library zlib and sockets
(standards on linux and unix). Basically if you are installing R from the
sources, you should be able to build a ACNUC socket server. 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Technical description of the racnucd daemon.}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Technical information about the acnuc socket server is available at this url:
\begin{verbatim}
http://pbil.univ-lyon1.fr/databases/acnuc/racnucd.html
\end{verbatim}

\section{ACNUC remote access protocol.}
Description of the socket communication protocol with acnuc is availble at this url:
\begin{verbatim}
http://pbil.univ-lyon1.fr/databases/acnuc/remote_acnuc.html
\end{verbatim}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Setting a local ACNUC database to be queried by the server.}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

First of all yo need an ACNUC database, built by yourself or  downloaded from the PBIL ftp server.
An ACNUC database is composed of 2 sets of files:
\begin{itemize}
	\item  the acnuc index files 
	\item  the database files (i.e. flat files in EMBL/GenBank or SwissProt format)
\end{itemize}

These 2 sets will be located  in the \textit{acnuc} and  \textit{gcgacnuc} directories  respectively.
(Directories \textit{acnuc} and  \textit{gcgacnuc} may be identical however it is prefered to use two distict directories.)
An example of an ACNUC database is available on the PBIL ftp server  at this url:
\begin{verbatim}
ftp://pbil.univ-lyon1.fr/pub/seqinr/demoacnuc/acnucdatabase.tar.Z
\end{verbatim}. 
You may install the database as it follows:
Let ACNUC\_HOME be the base directory for ACNUC intallation.
\begin{itemize}
\item Dowload the ACNUC database.
\item Copy the  acnucdatabase.tar.Z file  into ACNUC\_HOME.
\item Uncompress and untar the  acnucdatabase.tar.Z file 
\end{itemize}
Now you sould get the following directories:
\begin{verbatim}
ACNUC_HOME/acnucdatabase/index
ACNUC_HOME/acnucdatabase/flat_files
\end{verbatim}
which are the   \textit{acnuc} and  \textit{gcgacnuc} directories  respectively.

This database contains the complete genome of \textit{Escherichia coli K12 W3110} and
\textit{Saccharomyces cerevesiae}.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Build the ACNUC sockets server from the sources.}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Once you have a local  ACNUC database available on your server you need to install the sockets server.

\subsection{Download the sources.}
The code source of the racnucd server is available on the PBIL server  at this url:
\begin{verbatim}
http://pbil.univ-lyon1.fr/databases/acnuc/racnucd.html
\end{verbatim}
Alternatively you can download directly  the source from the ftp at:
\begin{verbatim}
ftp://pbil.univ-lyon1.fr/pub/acnuc/unix/racnucd.tar
\end{verbatim}

\subsection{Build the ACNUC sockets server.}
You may install the racnucd server as it follows:
let RACNUCD\_HOME be the base directory for the socket
\begin{itemize}
\item Dowload the  racnucd.tar file
\item Copy the  racnucd.tar file   into RACNUCD\_HOME.
\item Untar the  racnucd.tar  file 
\end{itemize}
Now you sould get the following directory:
\begin{verbatim}
RACNUCD_HOME/racnucd
\end{verbatim}
Go into RACNUCD\_HOME/racnucd/ and type;
\begin{verbatim}
make
\end{verbatim}
This should create the \textbf{racnucd} executable.

\subsection{Setting the ACNUC sockets server.}
The server is configured by several parameters described in a configuration file \textbf{racnuc.ini}.
The \textbf{racnuc.ini} file is structued as follows:

\begin{verbatim}
port=5558
maxtime=8000
known_db_file=knowndbs
db_env_names=dbplaces
\end{verbatim}

\begin{itemize}
\item \textbf{knowndbs} is a file containing the list of available databases
\item \textbf{dbplaces} is a file containing the path of the available databases
\end{itemize}

The \textbf{knowndbs} contains:
\begin{verbatim}
embl | on |    | EMBL sequence data library | 
swissprot   | on |  | UniProt |
\end{verbatim}
Each line defines a database,  the four fields indicating respectively the name
 of the database, its status  (\textit{on} or \textit{off}), a tag and a short description.

 The \textbf{dbplaces} contains:
\begin{verbatim}
setenv  swissprot       '/Users/mgouy/Documents/acnuc/petite/swissprot /Users/mgouy/Documents/acnuc/petite/swissprot'
setenv  embl    '/Users/mgouy/Documents/acnuc/petite/embl /Users/mgouy/Documents/acnuc/petite/embl'
\end{verbatim}
Each line set the acnuc and gcgacnuc variables for each   database.

Then you should set the files \textbf{knowndbs} and \textbf{dbplaces} according to your installation.
Let's call the database you installed previously \textit{demoacnuc}.
Modify  the \textbf{knowndbs} as follows:
\begin{verbatim}
demoacnuc | on |    | Demo Database | 
\end{verbatim}

and modify  the \textbf{dbplaces} as follows:

\begin{verbatim}
setenv  demoacnuc       'ACNUC_HOME/acnucdatabase/index ACNUC_HOME/acnucdatabase/flat_files'
\end{verbatim}

Finaly, still in the RACNUCD\_HOME/racnucd/ directory, type
\begin{verbatim}
./racnucd racnucd.ini
\end{verbatim}

The server should launch and say:
\begin{verbatim}

*******************************************************
Start of remote acnuc server : Tue Oct 16 15:46:16 2007

\end{verbatim}

The server is now ready.

\subsection{Using seqinR to query your local socket server.}
Launch R, load the \textit{seqinr} library  and type

\begin{Schunk}
\begin{Sinput}
choosebank(host="my_machine.domaine",info=T)
\end{Sinput}
\end{Schunk}
for example:

\begin{Schunk}
\begin{Sinput}
choosebank(host="semle.univ-lyon1.fr",info=T)
\end{Sinput}

\begin{Soutput}
       bank status
1 demoacnuc     on
                                                                 info
1 ACNUC database example. (September 2007) Last Updated: Oct 15, 2007
\end{Soutput}
\end{Schunk}

You can now query the database.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{ACNUC sockets server binaries distributions. (under development)}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Binaries are available for several machines: 

\begin{itemize}
	\item  Unix sunOS
	\item  Linux RedHat
	\item Darwin Mac OS
\end{itemize}

You can download the different distribution at this address: 
(XXX to be done XXX ).

Then you can install the socket server :

Bla.. blah blah




%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Building your own  ACNUC database. (under development)}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
One of the interest of a local server is to be able use your own ACNUC
database.

 \subsection{System requirements.}
 
ACNUC runs on UNIX systems, Windows NT/95/98/00/XP, MacOS 9/X. Tested UNIX
systems include SUN, Linux on PC, IBM RS/6000, Silicon Graphics, DEC Alpha,
Fujitsu UXP/M. ACNUC should be easily installed on any other UNIX platforms. 

\subsection{Database requirements.}

ACNUC database are build from flat files in several possible format : EMBL, Genbank or
SwissProt.

\subsection{Download the ACNUC dababase management tools.}
 
\subsection{Install the ACNUC dababase management tools.}

\subsection{Database building}

\section{Misc} 
%%%%%%%%%%%%%

Other tools for acnuc

Several powerful tools dedicated to query ACNUC databases are available. 

The programs \textbf{query} and \textbf{query\_win} allow to query an ACNUC database according to the same
criteria than described  in seqinR. It allows as well several functionality to extact biological data.
\textbf{query\_win} is a graphical version of query.
\textbf{query} is an on-line version which allows to query and ACNUC database through scripts.
Both \textbf{query} and  \textbf{query\_win} are available as a
\textit{client} or a \textit{local} application. More information on these programs can be found at:
\begin{verbatim}
http://pbil.univ-lyon1.fr/software/query_win.html
\end{verbatim}. 




\section{Citation} 
%%%%%%%%%%%%%

If you use query\_win or query in a published work, please cite the following reference:
Gouy M, Gautier C, Attimonelli M, Lanave C, di Paola G. (1985)
 ACNUC--a portable retrieval system for nucleic acid sequence databases: 
 logical and physical designs and usage.. CABIOS, 1, 167-172. 


\SweaveInput{../config/sessionInfo.rnw}

% END - DO NOT REMOVE THIS LINE

%%%%%%%%%%%%  BIBLIOGRAPHY %%%%%%%%%%%%%%%%%
\clearpage
\addcontentsline{toc}{section}{References}
\bibliographystyle{plain}
\bibliography{../config/book}
\end{document}
